project:
  type: manuscript
  execute-dir: project

manuscript:
  article: paper.qmd
  notebooks:
    - notebooks/Analysis_01.qmd
    - notebooks/Data_collection.qmd

format:
  html:
    toc: true
  senshu-pdf: default

execute:
  freeze: auto
